import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'
import Footer from '../components/Footer';
import { ThemeProvider } from "next-themes";
import {
  ClerkProvider,
 
} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider  publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
 >
         <ThemeProvider
            attribute="class" 
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>
        <Navbar />
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}
